"""add beer presentation minimum stock

Revision ID: 051387c8f0b7
Revises: d13e9e25187e
Create Date: 2026-08-09 09:30:27.344633

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "051387c8f0b7"
down_revision: Union[str, Sequence[str], None] = "d13e9e25187e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "beer_presentations",
        sa.Column("minimum_stock", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_check_constraint(
        "ck_beer_presentations_minimum_stock_non_negative",
        "beer_presentations",
        "minimum_stock >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_beer_presentations_minimum_stock_non_negative",
        "beer_presentations",
        type_="check",
    )
    op.drop_column("beer_presentations", "minimum_stock")
    # ### end Alembic commands ###
