"""add production batch completion fields

Revision ID: 15b12bfb7534
Revises: b6893558d05d
Create Date: 2026-08-04 06:47:56.350671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15b12bfb7534"
down_revision: Union[str, Sequence[str], None] = "b6893558d05d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_batches",
        sa.Column(
            "produced_volume_liters", sa.Numeric(precision=10, scale=3), nullable=True
        ),
    )
    op.add_column(
        "production_batches", sa.Column("completed_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "raw_material_stock_movements",
        sa.Column("production_batch_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_raw_material_stock_movements_production_batch_id",
        "raw_material_stock_movements",
        "production_batches",
        ["production_batch_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_raw_material_stock_movements_production_batch_id",
        "raw_material_stock_movements",
        type_="foreignkey",
    )
    op.drop_column("raw_material_stock_movements", "production_batch_id")
    op.drop_column("production_batches", "completed_at")
    op.drop_column("production_batches", "produced_volume_liters")
    # ### end Alembic commands ###
