"""create beer presentation packaging materials table

Revision ID: 1b8597293fd4
Revises: f308fc626b04
Create Date: 2026-08-05 07:00:57.568596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8597293fd4'
down_revision: Union[str, Sequence[str], None] = 'f308fc626b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_presentation_packaging_materials',
    sa.Column('beer_presentation_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_quantity > 0', name='ck_bppm_required_quantity_positive'),
    sa.ForeignKeyConstraint(['beer_presentation_id'], ['beer_presentations.id'], ),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beer_presentation_id', 'raw_material_id', name='uq_bppm_presentation_id_raw_material_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer_presentation_packaging_materials')
    # ### end Alembic commands ###
