"""create sales tables

Revision ID: 406fe8f1f8a3
Revises: 9e48b2fcb8c9
Create Date: 2026-08-07 07:15:59.031733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "406fe8f1f8a3"
down_revision: Union[str, Sequence[str], None] = "9e48b2fcb8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "completed", "cancelled", name="sale_status"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "sale_items",
        sa.Column("sale_id", sa.Integer(), nullable=False),
        sa.Column("beer_presentation_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_sale_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price >= 0", name="ck_sale_items_unit_price_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["beer_presentation_id"],
            ["beer_presentations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sale_id",
            "beer_presentation_id",
            name="uq_sale_items_sale_id_beer_presentation_id",
        ),
    )
    op.add_column(
        "beer_presentation_stock_movements",
        sa.Column("sale_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_bpsm_sale_id",
        "beer_presentation_stock_movements",
        "sales",
        ["sale_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_bpsm_sale_id",
        "beer_presentation_stock_movements",
        type_="foreignkey",
    )
    op.drop_column("beer_presentation_stock_movements", "sale_id")
    op.drop_table("sale_items")
    op.drop_table("sales")
    # ### end Alembic commands ###
