"""create beer presentation stock movements

Revision ID: 4b3b4473dd4e
Revises: a05fc8dcf443
Create Date: 2026-08-06 19:04:13.270152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3b4473dd4e'
down_revision: Union[str, Sequence[str], None] = 'a05fc8dcf443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_presentation_stock_movements',
    sa.Column('beer_presentation_id', sa.Integer(), nullable=False),
    sa.Column('packaging_run_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('packaging_receipt', 'sale', 'initial_balance', 'waste', 'expiration', 'inventory_adjustment_in', 'inventory_adjustment_out', name='beer_presentation_stock_movement_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_bpsm_quantity_positive'),
    sa.ForeignKeyConstraint(['beer_presentation_id'], ['beer_presentations.id'], ),
    sa.ForeignKeyConstraint(['packaging_run_id'], ['packaging_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_check_constraint(
        "ck_beer_presentations_current_stock_non_negative",
        "beer_presentations",
        "current_stock >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_beer_presentations_current_stock_non_negative",
        "beer_presentations",
        type_="check",
    )
    op.drop_table('beer_presentation_stock_movements')
    # ### end Alembic commands ###
