"""create recipes table

Revision ID: 69c6cdb50100
Revises: bb670d6cca5a
Create Date: 2026-07-30 06:44:56.194718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c6cdb50100'
down_revision: Union[str, Sequence[str], None] = 'bb670d6cca5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "recipes",
        sa.Column("beer_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "target_volume_liters",
            sa.Numeric(precision=10, scale=3),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version > 0",
            name="ck_recipes_version_positive",
        ),
        sa.CheckConstraint(
            "target_volume_liters > 0",
            name="ck_recipes_target_volume_liters_positive",
        ),
        sa.ForeignKeyConstraint(
            ["beer_id"],
            ["beers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "beer_id",
            "version",
            name="uq_recipes_beer_id_version",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
