"""create delivery orders

Revision ID: 6ed85a92d073
Revises: 9adbacbb9944
Create Date: 2026-09-01 20:33:53.077585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ed85a92d073"
down_revision: Union[str, Sequence[str], None] = "9adbacbb9944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE beer_presentation_stock_movement_type "
        "ADD VALUE IF NOT EXISTS 'delivery'"
    )
    op.create_table(
        "delivery_orders",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("delivery_note_code", sa.String(length=30), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "picking",
                "delivered_pending_pricing",
                "closed",
                "cancelled",
                name="delivery_order_status",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("delivered_by_user_id", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("closed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("delivery_note_code"),
    )
    op.create_table(
        "delivery_order_items",
        sa.Column("delivery_order_id", sa.Integer(), nullable=False),
        sa.Column("beer_presentation_id", sa.Integer(), nullable=False),
        sa.Column("requested_quantity", sa.Integer(), nullable=False),
        sa.Column("picked_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "delivered_quantity", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivered_quantity <= picked_quantity",
            name="ck_delivery_order_items_delivered_quantity_not_above_picked",
        ),
        sa.CheckConstraint(
            "delivered_quantity >= 0",
            name="ck_delivery_order_items_delivered_quantity_non_negative",
        ),
        sa.CheckConstraint(
            "picked_quantity <= requested_quantity",
            name="ck_delivery_order_items_picked_quantity_not_above_requested",
        ),
        sa.CheckConstraint(
            "picked_quantity >= 0",
            name="ck_delivery_order_items_picked_quantity_non_negative",
        ),
        sa.CheckConstraint(
            "requested_quantity > 0",
            name="ck_delivery_order_items_requested_quantity_positive",
        ),
        sa.ForeignKeyConstraint(
            ["beer_presentation_id"],
            ["beer_presentations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_order_id"],
            ["delivery_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "delivery_order_id",
            "beer_presentation_id",
            name="uq_delivery_order_items_order_presentation",
        ),
    )
    op.create_table(
        "delivery_order_kegs",
        sa.Column("delivery_order_id", sa.Integer(), nullable=False),
        sa.Column("keg_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["delivery_order_id"],
            ["delivery_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keg_id"],
            ["kegs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "delivery_order_id", "keg_id", name="uq_delivery_order_kegs_order_keg"
        ),
    )
    op.add_column(
        "beer_presentation_stock_movements",
        sa.Column("delivery_order_id", sa.Integer(), nullable=True),
    )

    op.add_column(
        "keg_movements", sa.Column("delivery_order_id", sa.Integer(), nullable=True)
    )

    op.add_column("sales", sa.Column("delivery_order_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_bpsm_delivery_order_id",
        "beer_presentation_stock_movements",
        "delivery_orders",
        ["delivery_order_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_keg_movements_delivery_order_id",
        "keg_movements",
        "delivery_orders",
        ["delivery_order_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "uq_sales_delivery_order_id",
        "sales",
        ["delivery_order_id"],
    )
    op.create_foreign_key(
        "fk_sales_delivery_order_id",
        "sales",
        "delivery_orders",
        ["delivery_order_id"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_constraint(
        "fk_sales_delivery_order_id",
        "sales",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_sales_delivery_order_id",
        "sales",
        type_="unique",
    )
    op.drop_column("sales", "delivery_order_id")

    op.drop_constraint(
        "fk_keg_movements_delivery_order_id",
        "keg_movements",
        type_="foreignkey",
    )
    op.drop_column("keg_movements", "delivery_order_id")

    op.drop_constraint(
        "fk_bpsm_delivery_order_id",
        "beer_presentation_stock_movements",
        type_="foreignkey",
    )
    op.drop_column(
        "beer_presentation_stock_movements",
        "delivery_order_id",
    )

    op.drop_table("delivery_order_kegs")
    op.drop_table("delivery_order_items")
    op.drop_table("delivery_orders")
