"""create packaging runs

Revision ID: a05fc8dcf443
Revises: 1b8597293fd4
Create Date: 2026-08-05 20:06:59.240205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05fc8dcf443'
down_revision: Union[str, Sequence[str], None] = '1b8597293fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_runs',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=False),
    sa.Column('beer_presentation_id', sa.Integer(), nullable=False),
    sa.Column('packaged_quantity', sa.Integer(), nullable=False),
    sa.Column('packaged_volume_liters', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('packaged_quantity > 0', name='ck_packaging_runs_packaged_quantity_positive'),
    sa.CheckConstraint('packaged_volume_liters > 0', name='ck_packaging_runs_packaged_volume_positive'),
    sa.ForeignKeyConstraint(['beer_presentation_id'], ['beer_presentations.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('beer_presentations', sa.Column('current_stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('raw_material_stock_movements', sa.Column('packaging_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
    "fk_raw_material_stock_movements_packaging_run_id",
    "raw_material_stock_movements",
    "packaging_runs",
    ["packaging_run_id"],
    ["id"],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_raw_material_stock_movements_packaging_run_id",
    "raw_material_stock_movements",
    type_="foreignkey",
)
    op.drop_column('raw_material_stock_movements', 'packaging_run_id')
    op.drop_column('beer_presentations', 'current_stock')
    op.drop_table('packaging_runs')
    # ### end Alembic commands ###
