"""create production batches table

Revision ID: b6893558d05d
Revises: ed3789f0cfab
Create Date: 2026-08-02 11:37:13.208329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6893558d05d'
down_revision: Union[str, Sequence[str], None] = 'ed3789f0cfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_batches',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('planned_volume_liters', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('available_bulk_volume_liters', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='production_batch_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_bulk_volume_liters >= 0', name='ck_production_batches_available_bulk_volume_non_negative'),
    sa.CheckConstraint('planned_volume_liters > 0', name='ck_production_batches_planned_volume_positive'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_batches')
    # ### end Alembic commands ###
