"""create keg movements

Revision ID: b81c3dd7cb3b
Revises: ea1ca17bfdc3
Create Date: 2026-08-21 10:02:46.287922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b81c3dd7cb3b"
down_revision: Union[str, Sequence[str], None] = "ea1ca17bfdc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
existing_keg_status = postgresql.ENUM(
    "clean_available",
    "dirty",
    "filled",
    "at_customer",
    "tapped",
    "out_of_service",
    name="keg_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keg_movements",
        sa.Column("keg_id", sa.Integer(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "filling",
                "delivery",
                "return",
                "washing",
                "tapping",
                "remnant_transfer",
                "inventory_adjustment",
                "out_of_service",
                name="keg_movement_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_status",
            existing_keg_status,
            nullable=False,
        ),
        sa.Column(
            "new_status",
            existing_keg_status,
            nullable=False,
        ),
        sa.Column(
            "resulting_volume_liters", sa.Numeric(precision=10, scale=3), nullable=False
        ),
        sa.Column("beer_presentation_id", sa.Integer(), nullable=True),
        sa.Column("production_batch_id", sa.Integer(), nullable=True),
        sa.Column("packaging_run_id", sa.Integer(), nullable=True),
        sa.Column("sale_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resulting_volume_liters >= 0",
            name="ck_keg_movements_resulting_volume_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["beer_presentation_id"],
            ["beer_presentations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keg_id"],
            ["kegs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["packaging_run_id"],
            ["packaging_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["production_batch_id"],
            ["production_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("keg_movements")
    # ### end Alembic commands ###
