"""add sale cancellation fields

Revision ID: d13e9e25187e
Revises: 406fe8f1f8a3
Create Date: 2026-08-08 11:36:13.626464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13e9e25187e'
down_revision: Union[str, Sequence[str], None] = '406fe8f1f8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('sales', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'cancellation_reason')
    op.drop_column('sales', 'cancelled_at')
    # ### end Alembic commands ###
