"""create kegs table

Revision ID: ea1ca17bfdc3
Revises: 0a066df72f2c
Create Date: 2026-08-20 15:45:57.428971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1ca17bfdc3'
down_revision: Union[str, Sequence[str], None] = '0a066df72f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kegs',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('packaging_format_id', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.Enum('standard', 'flat', 'slim', name='keg_form_factor'), server_default='standard', nullable=False),
    sa.Column('status', sa.Enum('clean_available', 'dirty', 'filled', 'at_customer', 'tapped', 'out_of_service', name='keg_status'), server_default='clean_available', nullable=False),
    sa.Column('current_volume_liters', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('beer_presentation_id', sa.Integer(), nullable=True),
    sa.Column('production_batch_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_volume_liters >= 0', name='ck_kegs_current_volume_non_negative'),
    sa.ForeignKeyConstraint(['beer_presentation_id'], ['beer_presentations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['packaging_format_id'], ['packaging_formats.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('kegs')
    # ### end Alembic commands ###
