"""create recipe ingredients table

Revision ID: ed3789f0cfab
Revises: 69c6cdb50100
Create Date: 2026-07-31 06:58:45.658183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3789f0cfab'
down_revision: Union[str, Sequence[str], None] = '69c6cdb50100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('required_quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_quantity > 0', name='ck_recipe_ingredients_required_quantity_positive'),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'raw_material_id', name='uq_recipe_ingredients_recipe_id_raw_material_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    # ### end Alembic commands ###
