"""create beer presentations table

Revision ID: f308fc626b04
Revises: 7c2d4271aa57
Create Date: 2026-08-04 21:39:28.587534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f308fc626b04'
down_revision: Union[str, Sequence[str], None] = '7c2d4271aa57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_presentations',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('packaging_format_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['packaging_format_id'], ['packaging_formats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beer_id', 'packaging_format_id', name='uq_beer_presentations_beer_id_packaging_format_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer_presentations')
    # ### end Alembic commands ###
